# Generated by Django 2.0.2 on 2018-02-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShapeAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('type', models.CharField(choices=[('string', 'STRING'),], default='string', max_length=8)),
            ],
        ),
    ]
