# Generated by Django 2.0.2 on 2018-02-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0002_shapeattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='attributes',
            field=models.ManyToManyField(related_name='shapes', to='shapes.ShapeAttribute'),
        ),
    ]
