# Generated by Django 2.0.2 on 2018-02-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0005_shapeattribute_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapeattribute',
            name='type',
            field=models.CharField(choices=[('string', 'STRING'), ('integer', 'integer')], default='string', max_length=8),
        ),
        migrations.AlterField(
            model_name='shapeattributevalue',
            name='type',
            field=models.CharField(choices=[('string', 'STRING'), ('integer', 'integer')], default='string', max_length=8),
        ),
    ]
