# Generated by Django 2.0.2 on 2018-02-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0006_auto_20180220_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapeattribute',
            name='type',
            field=models.CharField(choices=[('string', 'STRING'), ('integer', 'INTEGER'), ('boolean', 'BOOLEAN')], default='string', max_length=8),
        ),
        migrations.AlterField(
            model_name='shapeattributevalue',
            name='type',
            field=models.CharField(choices=[('string', 'STRING'), ('integer', 'INTEGER'), ('boolean', 'BOOLEAN')], default='string', max_length=8),
        ),
    ]
