# Generated by Django 2.0.2 on 2018-02-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0008_shape_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='attributes',
            field=models.ManyToManyField(null=True, related_name='shapes', to='shapes.ShapeAttribute'),
        ),
    ]
