# Generated by Django 2.0.2 on 2018-02-21 23:39

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0008_shape_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapeattributevalue',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=models.CharField(max_length=64)),
        ),
    ]
